### PR TITLE
Create EX-cardfraud.jl

### PR DESCRIPTION
**Pull request by gd1989**
Based on Kristian Bjarnason's cardfraud script.

Edited script up to Neural Networks model (line 199). Review of last part of script to follow.

Note: the misclassification rate for the tuned LogisticClassifier is (consistently) higher than that of the non-tuned LogisticClassifier; on both the test and training sets... Although the difference is marginal (e.g.  0.00079 vs 0.0007856) I am currently not sure what's causing it.

### CODE REVIEW

**Comment by tlienart** [comment]
@kbjarnason would you like to have a quick look before I do a pass and bring this in?

**Comment by kbjarnason** [comment]
I'll have a look after work tomorrow if that's ok? Also did notice the
tuning could be a bit funny at times but towards the end I thought it gave
the same answer but apparently marginally off..

**Comment by tlienart** [comment]
sounds good thanks!!

**Comment by kbjarnason** [comment]
Just had a look through, it’s looking great!

Kind Regards,

Kristian Bjarnason

**Comment by gd1989** [comment]
Thanks Kristian!

Geoffroy

**Pull request merged**
