### PR TITLE
Added tutorial for UCI breast cancer classification dataset

### PR DESCRIPTION
**Pull request by adityasaini70**
Hey! I'm adding a tutorial for classification on the [UCI Breast Cancer Wisconsin(Diagnostic) dataset](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)). 

Please do suggest any improvements/suggestions whatsoever!

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks for that! I've had an overall look and it seems fine to me; same comment that I made to #145, I'm quite behind on the updating of this website so it might take me a while before I integrate your tutorial but thanks a lot for your contribution :)

**Comment by adityasaini70** [comment]
@tlienart No issues at all! I'd be more than happy to help you with the site too if you have any impending issues which need some work :D

**Comment by tlienart** [comment]
Cool, I'll make sure to ask you then :)

**Comment by tlienart** [comment]
thanks, I'll do some manual adjustments and merge this now

**Comment by tlienart** [comment]
it's live, and it's a pretty nice tutorial, well done and thanks!

**Comment by adityasaini70** [comment]
Awesome! Thanks a lot :D

**Pull request merged**
