### PR TITLE
LAB:  Using MLJ with the GLM package

### PR DESCRIPTION
**Pull request by drcxcruz**
"LAB:  Using MLJ with the GLM package"
to be reviewed my AlanTuring team

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks, I'll have a look

**Comment by tlienart** [comment]
Ps: sorry for the lack of feedback, I haven't yet had the time but it's on my todo!

**Comment by tlienart** [comment]
Hello @drcxcruz I'm glad to announce that your tutorial is now (finally!) in, please have a look at the live version: https://alan-turing-institute.github.io/DataScienceTutorials.jl/end-to-end/glm/

If you have comments, would like to add more explanations or plots etc, please don't hesitate to reach out and thanks a lot for this contribution!

cc:  @ablaom

**Comment by drcxcruz** [comment]
hi,

I am super glad about it.  it looks great!!!

should I create a new github pull request for the other lab:
https://notes.quantecon.org/submission/5e653f616479ca001038be0f  ?  or you
can grab it from the notes site?

THANK YOU

**Comment by tlienart** [comment]
Are you happy for us to grab it from there? And should I give credits to you or someone else?

Maybe you can open an issue with the details and we’ll do the rest :)

Thanks a lot!

**Pull request merged**
