### PR TITLE
projectifying every tutorial

### PR DESCRIPTION
**Pull request by tlienart**
Makes every tutorial have its own project to avoid name clashes and other unpleasantness. Should make longer term maintenance much easier and avoid doing random named imports

* [x] A
* [x] D0
* [x] EX
* [x] ISL

### CODE REVIEW

**Comment by ablaom** [comment]
@tlienart Just a friendly reminder that we are excited by the prospect of further progress on this PR 😉

**Comment by tlienart** [comment]
I made good progress today, Julia's Pkg system is very very painful though, I don't know how many times I've seen it precompile DataFrames and other packages that I use everywhere.... 


I'm still getting a few errors which I can't fix:

* EvoTrees and CUDA have an installation problem for the `getting-started/stacking` 
* There's a `level not defined` error, stack trace:

```
TaskFailedException

    nested task error: UndefVarError: level not defined
    Stacktrace:
     [1] fit_only!(mach::Machine{OneHotEncoder, true}, wait_on_downstream::Bool; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbosity,), Tuple{Int64}}})
       @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/machines.jl:563
     [2] (::MLJBase.var"#121#123"{Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbosity,), Tuple{Int64}}}, Machine{OneHotEncoder, true}})()
       @ MLJBase ./task.jl:411
    
    caused by: UndefVarError: level not defined
    Stacktrace:
     [1] getproperty
       @ ./Base.jl:35 [inlined]
     [2] int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalValue{Char, UInt32})
       @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/interface/data_utils.jl:22
     [3] int(x::CategoricalArrays.CategoricalValue{Char, UInt32}; type::Nothing)
       @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
     [4] int(x::CategoricalArrays.CategoricalValue{Char, UInt32})
       @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
     [5] fit(transformer::OneHotEncoder, verbosity::Int64, X::NamedTuple{(:age, :gender), Tuple{Vector{Float64}, CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}}})
       @ MLJModels ~/.julia/packages/MLJModels/E8BbE/src/builtins/Transformers.jl:1146
     [6] fit_only!(mach::Machine{OneHotEncoder, true}; rows::Nothing, verbosity::Int64, force::Bool)
       @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/machines.jl:470
     [7] fit_only!(mach::Machine{OneHotEncoder, true}, wait_on_downstream::Bool; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbosity,), Tuple{Int64}}})
       @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/machines.jl:559
     [8] (::MLJBase.var"#121#123"{Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbosity,), Tuple{Int64}}}, Machine{OneHotEncoder, true}})()
       @ MLJBase ./task.jl:411
sync_end(c::Channel{Any}) at task.jl:369
macro expansion at task.jl:388 [inlined]
fit!(y::Node{Nothing}, ::CPU1{Nothing}; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:verbosity,), Tuple{Int64}}}) at nodes.jl:199
fit! at nodes.jl:189 [inlined]
#fit!#117 at nodes.jl:181 [inlined]
fit! at nodes.jl:181 [inlined]
#fit!#176 at machines.jl:146 [inlined]
fit! at machines.jl:145 [inlined]
return!(mach::Machine{DeterministicSurrogate, false}, model::Pipeline368, verbosity::Int64) at machines.jl:279
(::MLJBase.var"#_fit#217"{Machine{DeterministicSurrogate, false}, Tuple{OneHotEncoder, NearestNeighborModels.KNNRegressor, UnivariateStandardizer}, Tuple{MLJBase.Source, MLJBase.Source, MLJBase.Source}})(::Pipeline368, ::Int64, ::NamedTuple{(:age, :gender), Tuple{Vector{Int64}, CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}}}, ::Vararg{Any}) at from_network.jl:25
fit(::Pipeline368, ::Int64, ::NamedTuple{(:age, :gender), Tuple{Vector{Int64}, CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}}}, ::Vector{Int64}) at from_network.jl:166
fit_only!(mach::Machine{Pipeline368, true}; rows::Vector{Int64}, verbosity::Int64, force::Bool) at machines.jl:470
fit_only! at machines.jl:423 [inlined]
#fit!#104 at machines.jl:537 [inlined]
fit! at machines.jl:535 [inlined]
fit_and_extract_on_fold at resampling.jl:865 [inlined]
(::MLJBase.var"#286#287"{MLJBase.var"#fit_and_extract_on_fold#308"{Vector{Tuple{Vector{Int64}, Vector{Int64}}}, Nothing, Nothing, Int64, Vector{RootMeanSquaredError}, typeof(predict), Bool, Bool, Vector{Int64}, NamedTuple{(:age, :gender), Tuple{Vector{Int64}, CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}}}}, Machine{Pipeline368, true}, Int64, ProgressMeter.Progress})(k::Int64) at resampling.jl:710
mapreduce_first at reduce.jl:394 [inlined]
_mapreduce(f::MLJBase.var"#286#287"{MLJBase.var"#fit_and_extract_on_fold#308"{Vector{Tuple{Vector{Int64}, Vector{Int64}}}, Nothing, Nothing, Int64, Vector{RootMeanSquaredError}, typeof(predict), Bool, Bool, Vector{Int64}, NamedTuple{(:age, :gender), Tuple{Vector{Int64}, CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}}}}, Machine{Pipeline368, true}, Int64, ProgressMeter.Progress}, op::typeof(vcat), #unused#::IndexLinear, A::UnitRange{Int64}) at reduce.jl:405
_mapreduce_dim at reducedim.jl:330 [inlined]
#mapreduce#731 at reducedim.jl:322 [inlined]
mapreduce at reducedim.jl:322 [inlined]
_evaluate!(func::MLJBase.var"#fit_and_extract_on_fold#308"{Vector{Tuple{Vector{Int64}, Vector{Int64}}}, Nothing, Nothing, Int64, Vector{RootMeanSquaredError}, typeof(predict), Bool, Bool, Vector{Int64}, NamedTuple{(:age, :gender), Tuple{Vector{Int64}, CategoricalArrays.CategoricalVector{Char, UInt32...
```

(A-composite-models/tutorial.jl)


I'm slowly progressing through the rest, will do what I can and just flag the ones that fail.

**Comment by tlienart** [comment]
level issue with:

```julia
using MLJ
import Statistics
using PrettyPrinting
using StableRNGs

MLJ.color_off() # hide
X, y = @load_iris;

DecisionTreeClassifier = @load DecisionTreeClassifier pkg=DecisionTree
tree_model = DecisionTreeClassifier()

tree = machine(tree_model, X, y)

rng = StableRNG(566)
train, test = partition(eachindex(y), 0.7, shuffle=true, rng=rng)
test[1:3]

fit!(tree, rows=train)
```

maybe related to DT, stacktrace

```
UndefVarError: level not defined
getproperty at Base.jl:35 [inlined]
int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalValue{String, UInt32}) at data_utils.jl:22
int(x::CategoricalArrays.CategoricalValue{String, UInt32}; type::Nothing) at data_utils.jl:73
int(x::CategoricalArrays.CategoricalValue{String, UInt32}) at data_utils.jl:73
_broadcast_getindex_evalf at broadcast.jl:670 [inlined]
_broadcast_getindex at broadcast.jl:643 [inlined]
getindex at broadcast.jl:597 [inlined]
copy at broadcast.jl:943 [inlined]
materialize at broadcast.jl:904 [inlined]
int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}}) at data_utils.jl:18
int(x::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}}; type::Nothing) at data_utils.jl:73
int(x::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}}) at data_utils.jl:73
fit(m::MLJDecisionTreeInterface.DecisionTreeClassifier, verbosity::Int64, X::NamedTuple{(:sepal_length, :sepal_width, :petal_length, :petal_width), NTuple{4, Vector{Float64}}}, y::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}}) at MLJDecisionTreeInterface.jl:95
fit_only!(mach::Machine{MLJDecisionTreeInterface.DecisionTreeClassifier, true}; rows::Vector{Int64}, verbosity::Int64, force::Bool) at machines.jl:470
fit_only! at machines.jl:423 [inlined]
#fit!#104 at machines.jl:537 [inlined]
(::StatsBase.var"#fit!##kw")(::NamedTuple{(:rows,), Tuple{Vector{Int64}}}, ::typeof(fit!), mach::Machine{MLJDecisionTreeInterface.DecisionTreeClassifier, true}) at machines.jl:535
top-level scope at tutorial.jl:55
eval at boot.jl:373 [inlined]
```

version info

```
(A-fit-predict) pkg> status
      Status `~/.julia/dev/DataScienceTutorials/_literate/A-fit-predict/Project.toml`
  [add582a8] MLJ v0.16.2
  [c6f25543] MLJDecisionTreeInterface v0.1.2
  [54e16d92] PrettyPrinting v0.3.2
  [860ef19b] StableRNGs v1.0.0
  [10745b16] Statistics
```

**Comment by tlienart** [comment]
There's also a 

```
│ Details:
│ ArgumentError: Function `partition` only supports AbstractVector, AbstractMatrix or containers implementing the Tables interface.
│ Stacktrace:
│   [1] partition(X::SentinelArrays.IndexIterator{Vector{Float64}}, fractions::Float64; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:shuffle, :rng), Tuple{Bool, StableRNGs.LehmerRNG}}})
│     @ MLJBase ~/.julia/packages/MLJBase/De8Dv/src/data/data.jl:119
└
```

**Comment by tlienart** [comment]
urgh and I now get lots of issues with Conventions... this must be a scitype thing.

I'm not sure I'll manage to ever have the time to fix all this ... 😞

**Comment by tlienart** [comment]
Maybe more helpful, here's a list of what works and doesn't work + some indication of why if I know

## Data

all green

## ISL 

all green

## End2End

* XGB: `curve` not defined
* (minor) HKC: tuning gives a worse result
* Airfoil
* Boston LGBM
* GLM
* Power
* Boston Flux ; looks like it tries to do some crappy evaluation which ends up conflicting with Franklin (something `build`)

**Note** a few issues with `partition(eachindex(...)` had to replace by `partition(collect(eachindex` 

## Getting Started


(my laptop is crashing, will update this later...)

**Comment by ablaom** [comment]
I'm a little surprised you are having all these problems. Are you using Julia 1.6 (the latest official release) or something newer?

**Comment by tlienart** [comment]
@ablaom ok I cleaned up almost everything, there's now only **three** pages with problems which I'd like to have your eyes on:

1. `_literate/A-stacking/tutorial.jl` (there's maybe a bad call to RMS or something)
2. `_literate/EX-crabs-xgb/tutorial.jl` (there's a call to a `curve` function which is deprecated I think)
3. `_literate/EX-boston-flux/tutorial.jl` (this one completely fails for me)

If you could try cloning this branch and fixing those three, that should be it.

**Comment by tlienart** [comment]
Ok so I imagine you're super busy and given it's probably better this just goes forward, I'll disable the three tutorials mentioned above, publish the updated website and open 3 issues "to be fixed" later.

**Comment by ablaom** [comment]
Ahh. The bug in the stacking example looks like a bug in EvoTrees.jl reported to me by @lhnguyen-vn .

@lhnguyen-vn can you please post an issue at EvoTrees.jl as discussed?

**Pull request merged**
