### PR TITLE
ongoing update of tutorials

### PR DESCRIPTION
**Pull request by tlienart**
cc: @ablaom @okonsamuel @giordano 

Sorry for being so slow here, I will have some time in the short-medium term to do a bunch of much needed fixes here to help longer term maintainability etc.

The first step is to get all tutorials working with 0.16. I'm mostly there following the work started by @giordano in #148  with a few exceptions I'd like help with (these should be easy to fix I would think):

* [ ] `A-ensembles-3` (something about bad hyper parameter type inference) 
* [ ] `Learning networks 2` some warning about calling `machine` with no arguments
* [ ] `A-stacking` there's likely some bug in the syntax that causes a crash
* [ ] `EX-AMES` (a fitting problem)
* [ ] `EX-GLM` a bunch of issues seemingly with the ways functions are called

Could I get help with those please? They should work, standalone, once you activate the environment. Once this is fixed I can work on the Franklin side of things.

The steps on your side would be to checkout this branch, activate the environment run one of those scripts, fix the errors and push here.

PS: I've not checked whether the tutorials give sensible results, nor tried to be coherent in how things are called that can be for another iteration.
PPS: ignore Franklin, CI and all that jazz, I'll do that.

### CODE REVIEW

**Comment by ablaom** [comment]
I think I can take a look at this tomorrow.

**Comment by ablaom** [comment]
I'm having trouble instantiating the current env.

Under julia 1.5 and jula 1.6

```julia
(DataScienceTutorials) pkg> instantiate
ERROR: AssertionError: sourcepath !== nothing
Stacktrace:
 [1] is_package_downloaded at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1670 [inlined]
 [2] #12 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:113 [inlined]
```

I can instantiate from the Project.toml (`]instantiate -p`) but that defeats the whole purpose of reproducibility. And if I am having this problem, so presumably will users.

For now proceeding using the modified Manifest.toml .

**Comment by giordano** [comment]
The environment must be created with Julia v1.5, so that it can be instantiated with both Julia v1.5 and v1.6.  This is what I did in https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/148/commits/4ddf48ba8d73667e017efad4ccbca6cd680cc763

**Comment by ablaom** [comment]
Then I'll re-create the env using julia 1.5 and we can use whatever `instantiate -p` gives me.

**Comment by ablaom** [comment]
Mmm, that manifest doesn't seem to be correct either:

```julia
(DataScienceTutorials) pkg> instantiate
ERROR: `MLJClusteringInterface` is a direct dependency, but does not appear in the manifest. If you intend `MLJClusteringInterface` to be a direct dependency, run `Pkg.resolve()` to populate the manifest. Otherwise, remove `MLJClusteringInterface` with `Pkg.rm("MLJClusteringInterface")`. Finally, run `Pkg.instantiate()` again.
```

**Comment by giordano** [comment]
This `Manifest.toml` works for me for both Julia v1.5 and v1.6: https://gist.github.com/giordano/6cb86e225482497d123981a20cfae8cb.

**Comment by ablaom** [comment]
Okay. I regenerated a new Manifest.toml using Julia 1.5 (not @giordano's one) and worked with that. I'm opening a new PR with my changes here https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/151 (currently passing CI)

**Pull request closed without merging**
